const stringToType = require('utils/stringToType');

// parses an lnd.conf formatted string and returns a JavaScript object
const parse = (lndConfigString) => {
  const lines = lndConfigString.split(/\r?\n/).filter(line => line.trim() !== '');
  
  const configObject = {};
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('#') || line.startsWith(';') || line.startsWith('[')) continue;
    // a line that sets nothing (lnd itself would refuse it)
    if (!line.includes('=')) continue;
    // only split on the first "=", to allow for "=" in values (e.g., alias=my node = awesome)
    // keys trimmed too: "bridgerpc.enabled = true" is the key lnd reads
    const [rawKey, value] = line.split(/=(.*)/);
    const key = rawKey.trim();
    if (MULTILINE_KEYS.includes(key)) {
      if (! (key in configObject)) {
        configObject[key] = [];
      }
      // whitespace trimmed to handle user lnd.conf files with extra whitespace
      configObject[key].push(value.trim());
    } else {
      // whitespace trimmed to handle user lnd.conf files with extra whitespace
      configObject[key] = value.trim();
    }
  }
  return configObject;
}

// A key or value that would end its line early, and so write a line of its
// own into the file lnd reads. Nothing the dashboard writes legitimately
// contains one; refused outright rather than cleaned, so a bad value is
// noticed instead of quietly changed.
const LINE_BREAK = /[\r\n\0]/;
const KEY = /^[A-Za-z0-9._-]+$/;

function checkLine(key, value) {
  if (!KEY.test(key)) {
    throw new Error(`refusing to write the lnd.conf key ${JSON.stringify(key)}`);
  }
  if (LINE_BREAK.test(String(value))) {
    throw new Error(`refusing to write ${key}: its value contains a line break`);
  }
}

// returns an lnd.conf formatted string from a JavaScript object
const generate = (configObject) => {
  // Two header lines, which isUmbrelLndConfUpToDate skips when comparing.
  const first = process.env.DASHBOARD_PLATFORM === "native"
    ? "# Written by the Lightning Fork dashboard from lnd.conf and its own settings. Edit lnd.conf, not this file."
    : "# This file is automatically generated by Umbrel, any changes will be overwritten.";
  let lndConfigString = `${first}\n# Generated at: ${new Date().toISOString()}`;

  for (const [key, value] of Object.entries(configObject)) {

    // handles LND 0.16.0-beta breaking change for routerrpc apriori config options
    const formattedKey = KEY_TRANSLATIONS[key] || key;

    // alias guard clause here is to allow lnd to generate default alias if user doesn't set one
    if (formattedKey === "alias" && value === "") continue;
    // externalip guard clause here is to not write an empty externalip line to the umbrel-lnd.conf (which will cause lnd to fail to start)
    if (formattedKey === "externalip" && value.length === 0) continue;
    // likewise the watchtower's: empty means Tor only
    if (formattedKey === "watchtower.externalip" && !value) continue;
    if (Array.isArray(value)) {
      for (const item of value) {
        checkLine(formattedKey, item);
        lndConfigString += `\n${formattedKey}=${item}`;
      }
    } else {
      checkLine(formattedKey, value);
      lndConfigString += `\n${formattedKey}=${value}`;
    }
  }

  return lndConfigString;
}

// extracts the umbrel-managed settings from the config
// and applies the correct data types to the values
const getManagedConfig = (config, allowedConfig) => {
  let managedConfig = {};

  for (const [key, value] of Object.entries(config)) {

    // handles LND 0.16.0-beta breaking change for routerrpc apriori config options
    const formattedKey = INVERSE_KEY_TRANSLATIONS[key] || key;

    if (formattedKey in allowedConfig) {
      // stringToType is used to convert strings-values from a users lnd.conf to correct type.
      try {
        managedConfig[formattedKey] = stringToType(formattedKey, value);
      } catch (error) {
        // if the user has an invalid boolean value in their lnd.conf, we log the error and ignore it
        console.log("Failed to parse LND configuration.", error.message);
      }
    }
  }

  return managedConfig;
}

// Full list of settings - https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf
const MULTILINE_KEYS = [
  'externalip',
  'tlsextraip',
  'tlsextradomain',
  'externalhosts',
  'listen',
  'rpclisten',
  'restlisten',
  'restcors',
  'addpeer',
  'bitcoin.dnsseed',
  'watchtower.listen',
  'rpcmiddleware.addmandatory',
  'gossip.pinned-syncers'
];

const KEY_TRANSLATIONS = {
  'routerrpc.apriorihopprob': 'routerrpc.apriori.hopprob',
  'routerrpc.aprioriweight': 'routerrpc.apriori.weight',
  'routerrpc.penaltyhalflife': 'routerrpc.apriori.penaltyhalflife',
};

// Inverse of KEY_TRANSLATIONS to parse a user's lnd.conf correctly if they are using the legacy keys
const INVERSE_KEY_TRANSLATIONS = [];
for (const [key, value] of Object.entries(KEY_TRANSLATIONS)) {
  INVERSE_KEY_TRANSLATIONS[value] = key;
}

module.exports = {
  parse,
  generate,
  getManagedConfig
}
